export const actionDescriptions = {
  confused: "Expresses confusion or lack of understanding.",
  disappointed: "Shows disapproval or dissatisfaction.",
  shrug: "Indicates uncertainty or indifference.",
  understandnod: "Signals understanding or agreement.",
  wavingcalm: "A calm, gentle wave; often used as a subtle greeting or goodbye.",
  headaffirmdown: "Affirms agreement with a downward head nod.",
  headaffirmup: "Affirms agreement with an upward head nod.",
  headshakeslow: "Gently indicates disagreement or disapproval.",
  headshakemedium: "Clearly shows disagreement or negation.",
  headshakefast: "Emphatically signals strong disagreement.",
  wavehello: "A friendly greeting gesture.",
  fingerscrossed: "Expresses hope or wishing for good luck.",
  hearthands: "Shows affection, love, or gratitude.",
  okhand: "Signals that everything is fine or okay.",
  peacehand: "Conveys peace, goodwill, or a casual goodbye.",
  raisehand: "Signals a desire to speak, ask a question, or volunteer.",
  vulcansalute: "A pop culture gesture meaning 'Live long and prosper.'",
  wavebye: "Used to say goodbye in a friendly manner.",
  wavesalute: "A respectful or formal wave gesture.",
  admirenails: "Displays confidence or playful arrogance.",
  bow: "Shows respect or humility in a casual way.",
  callme: "Invites someone to contact or call.",
  clap: "Expresses praise, celebration, or agreement.",
  facepalm: "Indicates frustration, embarrassment, or disbelief.",
  fingerguns: "Playful gesture to show approval or friendliness.",
  fistbump: "A friendly gesture of camaraderie or agreement.",
  flexbiceps: "Shows off strength or confidence.",
  headnodfast: "Quickly signals strong agreement or encouragement.",
  headnodmedium: "Moderately affirms agreement or attentiveness.",
  headnodslow: "Gently shows understanding or contemplation.",
  horns: "Expresses enthusiasm or 'rock on' energy.",
  loveyou: "Expresses love or deep affection.",
  nervous: "Displays anxiety or discomfort.",
  pray: "Conveys hope, gratitude, or a spiritual plea.",
  thinking: "Indicates deep thought or consideration.",
  thumbsdown: "Expresses disapproval or rejection.",
  thumbsup: "Signals approval or agreement.",
  wink: "Adds a playful or friendly emphasis.",
  bowformal: "A respectful, formal bow typically used in traditional Japanese culture."
}; 