export const actionDescriptions = {
  wavehello: "A friendly greeting gesture.",
  fingerscrossed: "Expresses hope or wishing for good luck.",
  hearthands: "Shows affection, love, or gratitude.",
  okhand: "Signals that everything is fine or okay.",
  peacehand: "Conveys peace, goodwill, or a casual goodbye.",
  raisehand: "Signals a desire to speak, ask a question, or volunteer.",
  vulcansalute: "A pop culture gesture meaning 'Live long and prosper.'",
  wavebye: "Used to say goodbye in a friendly manner.",
  wavesalute: "A respectful or formal wave gesture.",
  admirenails: "Displays confidence or playful arrogance.",
  bow: "Shows respect or humility in a casual way.",
  callme: "Invites someone to contact or call.",
  clap: "Expresses praise, celebration, or agreement.",
  facepalm: "Indicates frustration, embarrassment, or disbelief.",
  fingerguns: "Playful gesture to show approval or friendliness.",
  fistbump: "A friendly gesture of camaraderie or agreement.",
  flexbiceps: "Shows off strength or confidence.",
  horns: "Expresses enthusiasm or 'rock on' energy.",
  loveyou: "Expresses love or deep affection.",
  pray: "Conveys hope, gratitude, or a spiritual plea.",
  thinking: "Indicates deep thought or consideration.",
  thumbsdown: "Expresses disapproval or rejection.",
  thumbsup: "Signals approval or agreement.",
  wink: "Adds a playful or friendly emphasis.",
  bowformal: "A respectful, formal bow typically used in traditional Japanese culture."
}; 