# Application Configuration
app:
  name: "Deutsche Telekom"
  environment: "development" # development, staging, production

# Personas Configuration
personas:
  en:
    cloud: 
      CDN: "https://cdn-eu.uneeq.io/hosted-experience/deploy/index.js"  
      API: "https://api-eu.uneeq.io"
      key: "d909d65a-e278-432e-b026-b7f7caa031e4"
    miniprem: 
      CDN: "https://cdn-eu.uneeq.io/hosted-experience/deploy/index.js"
      API: "https://api-eu.uneeq.io"
      key: "d909d65a-e278-432e-b026-b7f7caa031e4"
  fr:
    cloud: 
      CDN: "https://cdn-eu.uneeq.io/hosted-experience/deploy/index.js"  
      API: "https://api-eu.uneeq.io"
      key: "d909d65a-e278-432e-b026-b7f7caa031e4"
    miniprem: 
      CDN: "https://cdn-eu.uneeq.io/hosted-experience/deploy/index.js"
      API: "https://api-eu.uneeq.io"
      key: "d909d65a-e278-432e-b026-b7f7caa031e4"


# Used for websocket connection and service token retrieval
backend:
  host: "localhost"
  ports:
    http: 3000
    ws: 3001
  key: "7d2eb1df09f9b54875e2e601d6192ec3333a0784d4c487ec1dc8937a2f97a04d"


# External API Configuration
apis:
  pixabay:
    api_key: "50712646-82cbedef68573681d2bf357f4"
    api_url: "https://pixabay.com/api/"